# Generated by Django 5.2.12 on 2026-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do leitor')),
                ('email', models.CharField(max_length=100, verbose_name='Email do leitor')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF do leitor')),
            ],
            options={
                'verbose_name': 'Leitor',
                'verbose_name_plural': 'Leitores',
            },
        ),
    ]
